SF_CLIENT_ID: 'my_client_id'
SF_CLIENT_KEY: 'my_client_key'
SF_SITE: 'https://site'
SF_TOKEN_PATH: '/path/to/token/service'
SF_PING_PATH: 'dummy/path'
SF_PAT_INF_PATH: 'dummy/path/'
SF_DOI_INF_PATH: 'dummy/path/'
SF_CAS_RN_PATH: 'dummy/path/'
SF_LK_PAT_PATH: 'dummy/path/'
SF_LK_DOI_PATH: 'dummy/path/'
SF_LK_CAS_PATH: 'dummy/path/'
SF_ANS_SUB_PATH: 'dummy/path/'
SF_ANS_REA_PATH: 'dummy/path/'
SF_PASS_PHRASE: "has to be a 256bit key (32 char)"
OAUTH_DEBUG: 'false'
